// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: postgres/postgres.proto

package postgres

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DrinkType int32

const (
	DrinkType_UNDEFINED_DRINK_TYPE DrinkType = 0 // TODO:
)

// Enum value maps for DrinkType.
var (
	DrinkType_name = map[int32]string{
		0: "UNDEFINED_DRINK_TYPE",
	}
	DrinkType_value = map[string]int32{
		"UNDEFINED_DRINK_TYPE": 0,
	}
)

func (x DrinkType) Enum() *DrinkType {
	p := new(DrinkType)
	*p = x
	return p
}

func (x DrinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DrinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_postgres_postgres_proto_enumTypes[0].Descriptor()
}

func (DrinkType) Type() protoreflect.EnumType {
	return &file_postgres_postgres_proto_enumTypes[0]
}

func (x DrinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DrinkType.Descriptor instead.
func (DrinkType) EnumDescriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{0}
}

type CreateBarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Address     string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateBarRequest) Reset() {
	*x = CreateBarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBarRequest) ProtoMessage() {}

func (x *CreateBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBarRequest.ProtoReflect.Descriptor instead.
func (*CreateBarRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBarRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBarRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateBarRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateBarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Address     string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UpdateBarRequest) Reset() {
	*x = UpdateBarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBarRequest) ProtoMessage() {}

func (x *UpdateBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBarRequest.ProtoReflect.Descriptor instead.
func (*UpdateBarRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBarRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBarRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateBarRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteBarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBarRequest) Reset() {
	*x = DeleteBarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBarRequest) ProtoMessage() {}

func (x *DeleteBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBarRequest.ProtoReflect.Descriptor instead.
func (*DeleteBarRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteBarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBarResponse) Reset() {
	*x = DeleteBarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBarResponse) ProtoMessage() {}

func (x *DeleteBarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBarResponse.ProtoReflect.Descriptor instead.
func (*DeleteBarResponse) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{3}
}

type ListBarsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageFilter *PageFilter `protobuf:"bytes,1,opt,name=page_filter,json=pageFilter,proto3" json:"page_filter,omitempty"`
	Address    string      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ListBarsRequest) Reset() {
	*x = ListBarsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarsRequest) ProtoMessage() {}

func (x *ListBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarsRequest.ProtoReflect.Descriptor instead.
func (*ListBarsRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{4}
}

func (x *ListBarsRequest) GetPageFilter() *PageFilter {
	if x != nil {
		return x.PageFilter
	}
	return nil
}

func (x *ListBarsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListBarsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bars []*Bar `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty"`
}

func (x *ListBarsResponse) Reset() {
	*x = ListBarsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarsResponse) ProtoMessage() {}

func (x *ListBarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarsResponse.ProtoReflect.Descriptor instead.
func (*ListBarsResponse) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{5}
}

func (x *ListBarsResponse) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

type GetBarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsNeededDrinks bool   `protobuf:"varint,2,opt,name=is_needed_drinks,json=isNeededDrinks,proto3" json:"is_needed_drinks,omitempty"`
}

func (x *GetBarRequest) Reset() {
	*x = GetBarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarRequest) ProtoMessage() {}

func (x *GetBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarRequest.ProtoReflect.Descriptor instead.
func (*GetBarRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{6}
}

func (x *GetBarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBarRequest) GetIsNeededDrinks() bool {
	if x != nil {
		return x.IsNeededDrinks
	}
	return false
}

type CreateDrinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string                     `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price       string                     `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	DrinkType   DrinkType                  `protobuf:"varint,3,opt,name=drink_type,json=drinkType,proto3,enum=postgres.DrinkType" json:"drink_type,omitempty"`
	Description string                     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	BarId       string                     `protobuf:"bytes,5,opt,name=bar_id,json=barId,proto3" json:"bar_id,omitempty"`
	Ingredients []*CreateIngredientRequest `protobuf:"bytes,6,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
}

func (x *CreateDrinkRequest) Reset() {
	*x = CreateDrinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDrinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDrinkRequest) ProtoMessage() {}

func (x *CreateDrinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDrinkRequest.ProtoReflect.Descriptor instead.
func (*CreateDrinkRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDrinkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDrinkRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CreateDrinkRequest) GetDrinkType() DrinkType {
	if x != nil {
		return x.DrinkType
	}
	return DrinkType_UNDEFINED_DRINK_TYPE
}

func (x *CreateDrinkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDrinkRequest) GetBarId() string {
	if x != nil {
		return x.BarId
	}
	return ""
}

func (x *CreateDrinkRequest) GetIngredients() []*CreateIngredientRequest {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

type UpdateDrinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price       string    `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	DrinkType   DrinkType `protobuf:"varint,4,opt,name=drink_type,json=drinkType,proto3,enum=postgres.DrinkType" json:"drink_type,omitempty"`
	Description string    `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UpdateDrinkRequest) Reset() {
	*x = UpdateDrinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDrinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDrinkRequest) ProtoMessage() {}

func (x *UpdateDrinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDrinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateDrinkRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDrinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDrinkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDrinkRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *UpdateDrinkRequest) GetDrinkType() DrinkType {
	if x != nil {
		return x.DrinkType
	}
	return DrinkType_UNDEFINED_DRINK_TYPE
}

func (x *UpdateDrinkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteDrinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDrinkRequest) Reset() {
	*x = DeleteDrinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDrinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDrinkRequest) ProtoMessage() {}

func (x *DeleteDrinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDrinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteDrinkRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDrinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDrinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDrinkResponse) Reset() {
	*x = DeleteDrinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDrinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDrinkResponse) ProtoMessage() {}

func (x *DeleteDrinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDrinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteDrinkResponse) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{10}
}

type ListDrinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageFilter *PageFilter `protobuf:"bytes,1,opt,name=page_filter,json=pageFilter,proto3" json:"page_filter,omitempty"`
	BarId      string      `protobuf:"bytes,2,opt,name=bar_id,json=barId,proto3" json:"bar_id,omitempty"`
}

func (x *ListDrinksRequest) Reset() {
	*x = ListDrinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDrinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrinksRequest) ProtoMessage() {}

func (x *ListDrinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrinksRequest.ProtoReflect.Descriptor instead.
func (*ListDrinksRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{11}
}

func (x *ListDrinksRequest) GetPageFilter() *PageFilter {
	if x != nil {
		return x.PageFilter
	}
	return nil
}

func (x *ListDrinksRequest) GetBarId() string {
	if x != nil {
		return x.BarId
	}
	return ""
}

type ListDrinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drinks []*Drink `protobuf:"bytes,1,rep,name=drinks,proto3" json:"drinks,omitempty"`
}

func (x *ListDrinksResponse) Reset() {
	*x = ListDrinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDrinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrinksResponse) ProtoMessage() {}

func (x *ListDrinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrinksResponse.ProtoReflect.Descriptor instead.
func (*ListDrinksResponse) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{12}
}

func (x *ListDrinksResponse) GetDrinks() []*Drink {
	if x != nil {
		return x.Drinks
	}
	return nil
}

type GetDrinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsNeededDrinks bool   `protobuf:"varint,2,opt,name=is_needed_drinks,json=isNeededDrinks,proto3" json:"is_needed_drinks,omitempty"`
}

func (x *GetDrinkRequest) Reset() {
	*x = GetDrinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDrinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDrinkRequest) ProtoMessage() {}

func (x *GetDrinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDrinkRequest.ProtoReflect.Descriptor instead.
func (*GetDrinkRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{13}
}

func (x *GetDrinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDrinkRequest) GetIsNeededDrinks() bool {
	if x != nil {
		return x.IsNeededDrinks
	}
	return false
}

type CreateIngredientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Amount  string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	DrinkId string `protobuf:"bytes,3,opt,name=drink_id,json=drinkId,proto3" json:"drink_id,omitempty"`
}

func (x *CreateIngredientRequest) Reset() {
	*x = CreateIngredientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngredientRequest) ProtoMessage() {}

func (x *CreateIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngredientRequest.ProtoReflect.Descriptor instead.
func (*CreateIngredientRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{14}
}

func (x *CreateIngredientRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateIngredientRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateIngredientRequest) GetDrinkId() string {
	if x != nil {
		return x.DrinkId
	}
	return ""
}

type UpdateIngredientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *UpdateIngredientRequest) Reset() {
	*x = UpdateIngredientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIngredientRequest) ProtoMessage() {}

func (x *UpdateIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIngredientRequest.ProtoReflect.Descriptor instead.
func (*UpdateIngredientRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateIngredientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateIngredientRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateIngredientRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type DeleteIngredientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteIngredientRequest) Reset() {
	*x = DeleteIngredientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIngredientRequest) ProtoMessage() {}

func (x *DeleteIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIngredientRequest.ProtoReflect.Descriptor instead.
func (*DeleteIngredientRequest) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteIngredientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteIngredientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteIngredientResponse) Reset() {
	*x = DeleteIngredientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIngredientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIngredientResponse) ProtoMessage() {}

func (x *DeleteIngredientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIngredientResponse.ProtoReflect.Descriptor instead.
func (*DeleteIngredientResponse) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{17}
}

type PageFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit string `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page  string `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *PageFilter) Reset() {
	*x = PageFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageFilter) ProtoMessage() {}

func (x *PageFilter) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageFilter.ProtoReflect.Descriptor instead.
func (*PageFilter) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{18}
}

func (x *PageFilter) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *PageFilter) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

type Bar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Address     string               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Description string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Drinks      []*Drink             `protobuf:"bytes,5,rep,name=drinks,proto3" json:"drinks,omitempty"`
	CreatedAt   *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Bar) Reset() {
	*x = Bar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{19}
}

func (x *Bar) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bar) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bar) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Bar) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bar) GetDrinks() []*Drink {
	if x != nil {
		return x.Drinks
	}
	return nil
}

func (x *Bar) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bar) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Drink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price       string               `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	DrinkType   DrinkType            `protobuf:"varint,4,opt,name=drink_type,json=drinkType,proto3,enum=postgres.DrinkType" json:"drink_type,omitempty"`
	Description string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	BarId       string               `protobuf:"bytes,6,opt,name=bar_id,json=barId,proto3" json:"bar_id,omitempty"`
	Ingredients []*Ingredient        `protobuf:"bytes,7,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	CreatedAt   *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Drink) Reset() {
	*x = Drink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Drink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drink) ProtoMessage() {}

func (x *Drink) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drink.ProtoReflect.Descriptor instead.
func (*Drink) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{20}
}

func (x *Drink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Drink) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Drink) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Drink) GetDrinkType() DrinkType {
	if x != nil {
		return x.DrinkType
	}
	return DrinkType_UNDEFINED_DRINK_TYPE
}

func (x *Drink) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Drink) GetBarId() string {
	if x != nil {
		return x.BarId
	}
	return ""
}

func (x *Drink) GetIngredients() []*Ingredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *Drink) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Drink) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Ingredient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Amount    string               `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	DrinkId   string               `protobuf:"bytes,4,opt,name=drink_id,json=drinkId,proto3" json:"drink_id,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_postgres_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_postgres_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient.ProtoReflect.Descriptor instead.
func (*Ingredient) Descriptor() ([]byte, []int) {
	return file_postgres_postgres_proto_rawDescGZIP(), []int{21}
}

func (x *Ingredient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ingredient) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ingredient) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Ingredient) GetDrinkId() string {
	if x != nil {
		return x.DrinkId
	}
	return ""
}

func (x *Ingredient) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Ingredient) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_postgres_postgres_proto protoreflect.FileDescriptor

var file_postgres_postgres_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x67,
	0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x67,
	0x72, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x74, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x62, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x61, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a,
	0x10, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x72, 0x52, 0x04,
	0x62, 0x61, 0x72, 0x73, 0x22, 0x49, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x61, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x69, 0x73, 0x5f, 0x6e, 0x65, 0x65, 0x64,
	0x65, 0x64, 0x5f, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0e, 0x69, 0x73, 0x4e, 0x65, 0x65, 0x64, 0x65, 0x64, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x22,
	0xf2, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65,
	0x73, 0x2e, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x64, 0x72, 0x69,
	0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x61, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x61, 0x72, 0x49, 0x64, 0x12,
	0x43, 0x0a, 0x0b, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0xa6, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x72, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x64, 0x72, 0x69, 0x6e, 0x6b,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6f,
	0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x24, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x61, 0x0a, 0x11, 0x4c, 0x69,
	0x73, 0x74, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x35, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x61, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x61, 0x72, 0x49, 0x64, 0x22, 0x3d, 0x0a,
	0x12, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x44,
	0x72, 0x69, 0x6e, 0x6b, 0x52, 0x06, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x4b, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x28, 0x0a, 0x10, 0x69, 0x73, 0x5f, 0x6e, 0x65, 0x65, 0x64, 0x65, 0x64, 0x5f, 0x64, 0x72, 0x69,
	0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x4e, 0x65, 0x65,
	0x64, 0x65, 0x64, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x62, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x22, 0x57, 0x0a,
	0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65,
	0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36, 0x0a,
	0x0a, 0x50, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x86, 0x02, 0x0a, 0x03, 0x42, 0x61, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x27, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x72, 0x69, 0x6e, 0x6b,
	0x52, 0x06, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xde,
	0x02, 0x0a, 0x05, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x64, 0x72, 0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67,
	0x72, 0x65, 0x73, 0x2e, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x64,
	0x72, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x61,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x61, 0x72, 0x49,
	0x64, 0x12, 0x36, 0x0a, 0x0b, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65,
	0x73, 0x2e, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x69, 0x6e,
	0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0xdb, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x64, 0x72, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x72, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x25, 0x0a,
	0x09, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x55, 0x4e,
	0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x44, 0x52, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x10, 0x00, 0x32, 0x90, 0x07, 0x0a, 0x0d, 0x42, 0x61, 0x72, 0x4d, 0x61, 0x70, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x61, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0d, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x72, 0x22, 0x00,
	0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x72, 0x12, 0x1a, 0x2e,
	0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x72, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72,
	0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x42, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x72, 0x12, 0x19, 0x2e,
	0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67,
	0x72, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x42, 0x61, 0x72,
	0x12, 0x17, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x72, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x12, 0x1c, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72,
	0x65, 0x73, 0x2e, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x12, 0x1c, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72,
	0x65, 0x73, 0x2e, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x12, 0x1c, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72,
	0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x72, 0x69, 0x6e, 0x6b, 0x12, 0x1b, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x38, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x12, 0x19,
	0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x21, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x49,
	0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x10, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x21, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x49, 0x6e,
	0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x21,
	0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x61, 0x70, 0x70, 0x2f, 0x6d,
	0x61, 0x69, 0x6e, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_postgres_postgres_proto_rawDescOnce sync.Once
	file_postgres_postgres_proto_rawDescData = file_postgres_postgres_proto_rawDesc
)

func file_postgres_postgres_proto_rawDescGZIP() []byte {
	file_postgres_postgres_proto_rawDescOnce.Do(func() {
		file_postgres_postgres_proto_rawDescData = protoimpl.X.CompressGZIP(file_postgres_postgres_proto_rawDescData)
	})
	return file_postgres_postgres_proto_rawDescData
}

var file_postgres_postgres_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_postgres_postgres_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_postgres_postgres_proto_goTypes = []interface{}{
	(DrinkType)(0),                   // 0: postgres.DrinkType
	(*CreateBarRequest)(nil),         // 1: postgres.CreateBarRequest
	(*UpdateBarRequest)(nil),         // 2: postgres.UpdateBarRequest
	(*DeleteBarRequest)(nil),         // 3: postgres.DeleteBarRequest
	(*DeleteBarResponse)(nil),        // 4: postgres.DeleteBarResponse
	(*ListBarsRequest)(nil),          // 5: postgres.ListBarsRequest
	(*ListBarsResponse)(nil),         // 6: postgres.ListBarsResponse
	(*GetBarRequest)(nil),            // 7: postgres.GetBarRequest
	(*CreateDrinkRequest)(nil),       // 8: postgres.CreateDrinkRequest
	(*UpdateDrinkRequest)(nil),       // 9: postgres.UpdateDrinkRequest
	(*DeleteDrinkRequest)(nil),       // 10: postgres.DeleteDrinkRequest
	(*DeleteDrinkResponse)(nil),      // 11: postgres.DeleteDrinkResponse
	(*ListDrinksRequest)(nil),        // 12: postgres.ListDrinksRequest
	(*ListDrinksResponse)(nil),       // 13: postgres.ListDrinksResponse
	(*GetDrinkRequest)(nil),          // 14: postgres.GetDrinkRequest
	(*CreateIngredientRequest)(nil),  // 15: postgres.CreateIngredientRequest
	(*UpdateIngredientRequest)(nil),  // 16: postgres.UpdateIngredientRequest
	(*DeleteIngredientRequest)(nil),  // 17: postgres.DeleteIngredientRequest
	(*DeleteIngredientResponse)(nil), // 18: postgres.DeleteIngredientResponse
	(*PageFilter)(nil),               // 19: postgres.PageFilter
	(*Bar)(nil),                      // 20: postgres.Bar
	(*Drink)(nil),                    // 21: postgres.Drink
	(*Ingredient)(nil),               // 22: postgres.Ingredient
	(*timestamp.Timestamp)(nil),      // 23: google.protobuf.Timestamp
}
var file_postgres_postgres_proto_depIdxs = []int32{
	19, // 0: postgres.ListBarsRequest.page_filter:type_name -> postgres.PageFilter
	20, // 1: postgres.ListBarsResponse.bars:type_name -> postgres.Bar
	0,  // 2: postgres.CreateDrinkRequest.drink_type:type_name -> postgres.DrinkType
	15, // 3: postgres.CreateDrinkRequest.ingredients:type_name -> postgres.CreateIngredientRequest
	0,  // 4: postgres.UpdateDrinkRequest.drink_type:type_name -> postgres.DrinkType
	19, // 5: postgres.ListDrinksRequest.page_filter:type_name -> postgres.PageFilter
	21, // 6: postgres.ListDrinksResponse.drinks:type_name -> postgres.Drink
	21, // 7: postgres.Bar.drinks:type_name -> postgres.Drink
	23, // 8: postgres.Bar.created_at:type_name -> google.protobuf.Timestamp
	23, // 9: postgres.Bar.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 10: postgres.Drink.drink_type:type_name -> postgres.DrinkType
	22, // 11: postgres.Drink.ingredients:type_name -> postgres.Ingredient
	23, // 12: postgres.Drink.created_at:type_name -> google.protobuf.Timestamp
	23, // 13: postgres.Drink.updated_at:type_name -> google.protobuf.Timestamp
	23, // 14: postgres.Ingredient.created_at:type_name -> google.protobuf.Timestamp
	23, // 15: postgres.Ingredient.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 16: postgres.BarMapService.CreateBar:input_type -> postgres.CreateBarRequest
	2,  // 17: postgres.BarMapService.UpdateBar:input_type -> postgres.UpdateBarRequest
	3,  // 18: postgres.BarMapService.DeleteBar:input_type -> postgres.DeleteBarRequest
	5,  // 19: postgres.BarMapService.ListBar:input_type -> postgres.ListBarsRequest
	7,  // 20: postgres.BarMapService.GetBar:input_type -> postgres.GetBarRequest
	8,  // 21: postgres.BarMapService.CreateDrink:input_type -> postgres.CreateDrinkRequest
	9,  // 22: postgres.BarMapService.UpdateDrink:input_type -> postgres.UpdateDrinkRequest
	10, // 23: postgres.BarMapService.DeleteDrink:input_type -> postgres.DeleteDrinkRequest
	12, // 24: postgres.BarMapService.ListDrink:input_type -> postgres.ListDrinksRequest
	14, // 25: postgres.BarMapService.GetDrink:input_type -> postgres.GetDrinkRequest
	15, // 26: postgres.BarMapService.CreateIngredient:input_type -> postgres.CreateIngredientRequest
	16, // 27: postgres.BarMapService.UpdateIngredient:input_type -> postgres.UpdateIngredientRequest
	17, // 28: postgres.BarMapService.DeleteIngredient:input_type -> postgres.DeleteIngredientRequest
	20, // 29: postgres.BarMapService.CreateBar:output_type -> postgres.Bar
	20, // 30: postgres.BarMapService.UpdateBar:output_type -> postgres.Bar
	4,  // 31: postgres.BarMapService.DeleteBar:output_type -> postgres.DeleteBarResponse
	6,  // 32: postgres.BarMapService.ListBar:output_type -> postgres.ListBarsResponse
	20, // 33: postgres.BarMapService.GetBar:output_type -> postgres.Bar
	21, // 34: postgres.BarMapService.CreateDrink:output_type -> postgres.Drink
	21, // 35: postgres.BarMapService.UpdateDrink:output_type -> postgres.Drink
	11, // 36: postgres.BarMapService.DeleteDrink:output_type -> postgres.DeleteDrinkResponse
	13, // 37: postgres.BarMapService.ListDrink:output_type -> postgres.ListDrinksResponse
	21, // 38: postgres.BarMapService.GetDrink:output_type -> postgres.Drink
	22, // 39: postgres.BarMapService.CreateIngredient:output_type -> postgres.Ingredient
	22, // 40: postgres.BarMapService.UpdateIngredient:output_type -> postgres.Ingredient
	18, // 41: postgres.BarMapService.DeleteIngredient:output_type -> postgres.DeleteIngredientResponse
	29, // [29:42] is the sub-list for method output_type
	16, // [16:29] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_postgres_postgres_proto_init() }
func file_postgres_postgres_proto_init() {
	if File_postgres_postgres_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_postgres_postgres_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBarsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBarsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDrinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDrinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDrinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDrinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDrinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDrinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDrinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIngredientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateIngredientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIngredientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIngredientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Drink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_postgres_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ingredient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_postgres_postgres_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_postgres_postgres_proto_goTypes,
		DependencyIndexes: file_postgres_postgres_proto_depIdxs,
		EnumInfos:         file_postgres_postgres_proto_enumTypes,
		MessageInfos:      file_postgres_postgres_proto_msgTypes,
	}.Build()
	File_postgres_postgres_proto = out.File
	file_postgres_postgres_proto_rawDesc = nil
	file_postgres_postgres_proto_goTypes = nil
	file_postgres_postgres_proto_depIdxs = nil
}
